project/apps/adminpage/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from apps.adminpage.views import (
    services,
    profile,
    account,
    dashboard,
    category,
    ticketing
)

app_name = 'adminpage'

urlpatterns = [
  path('dashboard',                             login_required(dashboard.index),            name='dashboard'),
  path('service/setprofilesync',                login_required(services.setprofilesync),    name='setprofilesync'),
  path('profile',                               login_required(profile.index),              name='profile'),


  path('account/', include([
      # =================================================[ LOAD PAGE ]=================================================
      path('table',                             login_required(account.table),              name='account_table'),
      path('role',                              login_required(account.role),               name='account_role'),
      path('add',                               login_required(account.add),                name='account_add'),        
      path('edit/<int:id>',                     login_required(account.edit),               name='account_edit'),
      path('edit_group/<int:id>',               login_required(account.edit_group),         name='account_edit_group'),
      
      # ==================================================[ SERVICE ]==================================================
      path('delrole/<int:userid>/<int:groupid>',login_required(account.delrole),            name='account_delrole'),
      path('deletelist',                        login_required(account.deletelist),         name='account_deletelist'),
      path('setisactive/<str:mode>',            login_required(account.setisactive),        name='account_setisactive'),
  ])), 


  path('category/', include([
      # =================================================[ LOAD PAGE ]=================================================
      path('table',                             login_required(category.table),             name='category_table'),
      path('add',                               login_required(category.add),               name='category_add'),
      path('edit/<int:id>',                     login_required(category.edit),              name='category_edit'),

      # ==================================================[ SERVICE ]==================================================
      path('deletelist',                        login_required(category.deletelist),        name='category_deletelist'),
  ])),    


path('setting/', include([
    path('tiket/', include([        
        path('kategori/table',                            login_required(ticketing.category_table),             name='setting.ticketing.category.table'),
        path('kategori/add',                              login_required(ticketing.category_add),               name='setting.ticketing.category.add'),
        path('kategori/<int:id>/edit',                    login_required(ticketing.category_edit),              name='setting.ticketing.category.edit'),
        path('kategori/deletelist',                       login_required(ticketing.category_deletelist),        name='setting.ticketing.category.deletelist'),

        path('tahap/table',                            login_required(ticketing.state_table),             name='setting.ticketing.state.table'),
        path('tahap/add',                              login_required(ticketing.state_add),               name='setting.ticketing.state.add'),
        path('tahap/<int:id>/edit',                    login_required(ticketing.state_edit),              name='setting.ticketing.state.edit'),
        path('tahap/deletelist',                       login_required(ticketing.state_deletelist),        name='setting.ticketing.state.deletelist'),        
    ])),    
])),

path('tiket/', include([      
    path('table',                             login_required(ticketing.user_ajuan_table),             name='ticketing.user.ajuan.table'),
    path('user_ajuan_json',                   login_required(ticketing.user_ajuan_json),             name='ticketing.user.ajuan.json'),
    path('add',                               login_required(ticketing.user_ajuan_add),               name='ticketing.user.ajuan.add'),
    path('<int:id>/edit/',                    login_required(ticketing.user_ajuan_edit),              name='ticketing.user.ajuan.edit'),      
    path('<int:id>/show/',                    login_required(ticketing.user_ajuan_show),              name='ticketing.user.ajuan.show'),
    path('<int:id>/delete/',                  login_required(ticketing.user_ajuan_delete),        name='ticketing.user.ajuan.delete'),
    path('<int:id>/change_status/',           login_required(ticketing.user_ajuan_change_status),        name='ticketing.user.ajuan.change_status'),
    path('<int:id>/answer/',                  login_required(ticketing.ticketanswer_json),              name='ticketing.ticketanswer.json'),
    path('<int:id>/rating/add',                  login_required(ticketing.user_ajuan_rating_add),       name='ticketing.user.ajuan.rating.add'),

    path('bpsdm/table',                        login_required(ticketing.bpsdm_ajuan_table),             name='ticketing.bpsdm.ajuan.table'),
    path('bpsdm/ajuan_json',                   login_required(ticketing.bpsdm_ajuan_json),             name='ticketing.bpsdm.ajuan.json'),
    path('<int:id>/bpsdm/show/',               login_required(ticketing.bpsdm_ajuan_show),              name='ticketing.bpsdm.ajuan.show'),      
    path('<int:id>/bpsdm/change_status/<str:status_code>',      login_required(ticketing.bpsdm_ajuan_change_status),        name='ticketing.bpsdm.ajuan.change_status'),
    path('<int:id>/bpsdm/edit_state',          login_required(ticketing.bpsdm_edit_state),             name='ticketing.bpsdm.ajuan.edit_state'),
  ])),    
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', include('apps.landingpage.urls', namespace='landingpage')),
    path('hijack/', include('hijack.urls')),
    path('admin/', admin.site.urls),
    path('authentication/', include('apps.authentication.urls', namespace='authentication')),
    path('adminpage/', include('apps.adminpage.urls', namespace='adminpage')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
        re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    ]

handler404 = 'apps.landingpage.views.home.error_404'

project/apps/adminpage/views/account.py
from django.http.response import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User, Group
from django.urls import reverse
from django.db import transaction

from apps.services.decorators import group_required
from apps.authentication.models import Profile, GroupDetails
from apps.authentication.forms.auth import FormSignUp, FormUserEdit
from apps.authentication.forms.groupdetails import FormGroupDetails
from apps.authentication.forms.profile import FormProfile

from apps.adminpage.models import TicketCategory, TicketAdmin

from json import dumps





# =====================================================================================================
#                                               LOAD PAGE
# =====================================================================================================

@group_required('admin')
def table(request):
    context = {}
    # ===[Load a CSS And JS File]===
    context['datatables']       = True
    context['tinydatepicker']   = False
    context['datetimepicker']   = False
    context['select2']          = False
    context['chosen']           = False
    context['dropzone']         = False
    context['summernote']       = False
    context['fullcalendar']     = False
    context['photoswipe']       = False
    context['maxlength']        = False
    context['inputmask']        = False
    context['moment']           = False
    context['duallistbox']      = False
    context['daterange']        = False
    context['countdown']        = False


    # ===[Fetch Data]===
    context['dataaccounts']    = User.objects.all().exclude(is_superuser=True).exclude(is_staff=True).order_by('id')
    
    
    # ===[Render Template]===
    return render(request, 'adminpage/account/table.html', context)



@group_required('admin')
def role(request):
    context = {}
    # ===[Load a CSS And JS File]===
    context['datatables']       = True
    context['tinydatepicker']   = False
    context['datetimepicker']   = False
    context['select2']          = False
    context['chosen']           = False
    context['dropzone']         = False
    context['summernote']       = False
    context['fullcalendar']     = False
    context['photoswipe']       = False
    context['maxlength']        = False
    context['inputmask']        = False
    context['moment']           = False
    context['duallistbox']      = False
    context['daterange']        = False
    context['countdown']        = False


    # ===[Load Form]===
    context['datagroup']        = Group.objects.all()

    # ===[Fetch Data]===
    context['datauser']         = {}
    context['datagrouplist']    = {}
    getalluser                  = User.objects.all().exclude(is_staff=True).exclude(is_superuser=True)

    for user in getalluser:
        for group in user.groups.all():
            try:
                context['datagrouplist'][group.name] = group.groupdetails.alias
                context['datauser'][group.name].append({'user':user, 'group':group})
            except Exception as e:
                context['datagrouplist'][group.name] = group.groupdetails.alias
                context['datauser'][group.name] = [{'user':user, 'group':group}]

    # ===[Render Template]===
    return render(request, 'adminpage/account/role.html', context)



@group_required('admin')
def edit_group(request, id):
    context = {}
    # ===[Load a CSS And JS File]===
    context['datatables']       = False
    context['tinydatepicker']   = False
    context['datetimepicker']   = False
    context['select2']          = False
    context['chosen']           = False
    context['dropzone']         = False
    context['summernote']       = False
    context['fullcalendar']     = False
    context['photoswipe']       = False
    context['maxlength']        = False
    context['inputmask']        = False
    context['moment']           = False
    context['duallistbox']      = False
    context['daterange']        = False
    context['countdown']        = False

    # ===[Check ID IsValid]===
    try:
        getgroupdetails = GroupDetails.objects.get(group_id=id)
    except GroupDetails.DoesNotExist:
        messages.error(request, 'Data Not Found!')
        return redirect('adminpage:account_role')


    # ===[Load Form]===
    context['formgroupdetails']     = FormGroupDetails(request.POST or None, instance=getgroupdetails)


    # ===[Editt Logic]===
    if request.POST:
        if context['formgroupdetails'].is_valid():
            context['formgroupdetails'].save()

            messages.success(request, 'Data Edited Successfully', extra_tags=dumps({
                'redirect'      : reverse('adminpage:account_role'), 
                'confbtntxt'    : 'Check Data',
                'cnclbtntxt'    : 'Cancel',
            }))
            return redirect('adminpage:account_edit_group', id=id)
        else:
            messages.error(request, context['formgroupdetails'].errors)


    # ===[Render Template]===
    return render(request, 'adminpage/account/edit_group.html', context)



@group_required('admin')
def add(request):
    context = {}
    # ===[Load a CSS And JS File]===
    context['datatables']       = False
    context['tinydatepicker']   = False
    context['datetimepicker']   = False
    context['select2']          = True
    context['chosen']           = False
    context['dropzone']         = False
    context['summernote']       = False
    context['fullcalendar']     = False
    context['photoswipe']       = False
    context['maxlength']        = False
    context['inputmask']        = True
    context['moment']           = False
    context['duallistbox']      = True
    context['daterange']        = False
    context['countdown']        = False

    # ===[Load Form]===
    context['formsignup']       = FormSignUp(request.POST or None)
    context['formprofile']      = FormProfile(request.POST or None, request.FILES or None)

    # ===[Fetch Data]===
    context['groups']           = Group.objects.all()
    context['ticket_category']  = TicketCategory.objects.all()

    if request.POST:
        if context['formsignup'].is_valid():
            if context['formprofile'].is_valid():
                user = context['formsignup'].save()

                usergroups = request.POST.getlist('duallistbox_groups[]')
                user.groups.clear()
                user.groups.set(usergroups)
                user.save()

                useradmintickets = request.POST.getlist('duallistbox_admintickets[]')
                TicketAdmin.objects.filter(user=user).delete()
                useradmincategories = TicketCategory.objects.filter(id__in=useradmintickets)            
                for category in useradmincategories:
                    TicketAdmin.objects.create(user=user, ticketcategory=category)
                user.save()

                profile = context['formprofile'].save(commit=False)
                profile.user = user
                profile.save()
                
                messages.success(request, 'Data Added Successfully', extra_tags=dumps({
                    'redirect'      : reverse('adminpage:account_table'), 
                    'confbtntxt'    : 'Check Data',
                    'cnclbtntxt'    : 'Cancel',
                }))
                return redirect('adminpage:account_add')
            else:
                messages.error(request, context['formprofile'].errors)
        else:
            messages.error(request, context['formsignup'].errors)
    
    
    # ===[Render Template]===
    return render(request, 'adminpage/account/add.html', context)



@group_required('admin')
def edit(request, id):
    context = {}
    # ===[Load a CSS And JS File]===
    context['datatables']       = False
    context['tinydatepicker']   = False
    context['datetimepicker']   = False
    context['select2']          = True
    context['chosen']           = False
    context['dropzone']         = False
    context['summernote']       = False
    context['fullcalendar']     = False
    context['photoswipe']       = False
    context['maxlength']        = False
    context['inputmask']        = True
    context['moment']           = False
    context['duallistbox']      = True
    context['daterange']        = False
    context['countdown']        = False
    

    # ===[Check ID IsValid]===
    try:
        user = User.objects.get(id=id)
        context['usergroups'] = user.groups.values_list('id',flat=True)
        context['useradmintickets'] = user.ticketadmin_user.values_list('ticketcategory__id',flat=True)        
    except User.DoesNotExist:
        messages.error(request, 'Data Not Found!')
        return redirect('adminpage:account_table')

    # ===[Load Form]===
    context['formsignup']       = FormUserEdit(request.POST or None, instance=user)
    context['formprofile']      = FormProfile(request.POST or None, request.FILES or None, instance=user.profile)


    # ===[Fetch Data]===
    context['groups']           = Group.objects.all()
    context['ticket_category']  = TicketCategory.objects.all()


    # ===[Editt Logic]===
    if request.POST:

        if context['formsignup'].is_valid():
            if context['formprofile'].is_valid():
                user = context['formsignup'].save()
                profile = context['formprofile'].save(commit=False)
                profile.user = user
                profile.save()

                if request.POST.get('password1') and request.POST.get('password2'):
                    if request.POST.get('password1') != request.POST.get('password2'):
                        messages.error(request, 'Confirm password is not the same.')
                        return redirect('adminpage:account_edit', id=id)
                    
                    elif len(request.POST.get('password1')) < 8:

project/apps/adminpage/views/services.py
from django.http.response import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.contrib import messages

from apps.services.utils import profilesync
from apps.services.session import setsession


def setprofilesync(request):
    if request.POST:
        user, is_success = profilesync(request.user)
        if is_success:
            setsession(request, user)
            # return JsonResponse({ 'status' : 'success', 'message' : 'Profile sync successful' })
            messages.success(request, 'Profile sync successful') 
        else:
            # return JsonResponse({ 'status' : 'error', 'message' : 'Failed to sync profile' }) 
            messages.error(request, 'Failed to sync profile')            
    else:        
        # return JsonResponse({ 'status' : 'error', 'message' : 'Failed to sync profile' })  
        messages.error(request, 'Failed to sync profile')      

    # ===[Redirect]===
    return redirect(request.META.get('HTTP_REFERER', 'adminpage:dashboard'))

project/apps/adminpage/templates/adminpage/account/role.html
{% extends 'adminpage/layout/base.html' %}
{% load adminpage_tags %}

{% block content %}
  <div class="page-content container">
    <div class="page-header border-0 pb-3">
      <h1 class="page-title text-primary-d2 text-150">
        {{ request.path|getUrlSegment:2 }}
        <small class="page-info text-secondary-d2 text-nowrap">
          <i class="fa fa-angle-double-right text-80"></i>
          {{ request.path|getUrlSegment:3 }}
        </small>
      </h1>

      <div class="page-tools mt-3 mt-sm-0 mb-sm-n1">
        <!-- dataTables search box will be inserted here dynamically -->
      </div>
    </div>



    <div class="card bcard h-auto">
      <form method="post" autocomplete="off" class="border-t-3 brc-blue-m2">

        <table id="datatable" class="d-style w-100 table text-dark-m1 text-95 border-y-1 brc-black-tp11 collapsed dtr-table tablerole">
          <!-- add `collapsed` by default ... it will be removed by default -->
          <!-- thead with .sticky-nav -->
          <thead class="sticky-nav text-secondary-m1 text-uppercase text-85">
            <tr>
              <th class="td-toggle-details border-0 bgc-white shadow-sm">
                <i class="fa fa-angle-double-down ml-2"></i>
              </th>

              <th class="border-0 bgc-white pl-3 pl-md-4 shadow-sm">
                <input type="checkbox" />
              </th>

              <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                No
              </th>

              <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                Name (System)
              </th>

              <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                Alias
              </th>

              <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                Description
              </th>

              <th class="border-0 bgc-white shadow-sm w-2">
                Action
              </th>
            </tr>
          </thead>

          <tbody class="pos-rel">
            {% if datagroup %}
            {% for data in datagroup %}
            <tr class="d-style bgc-h-default-l4">
              <td class="td-toggle-details pos-rel">
                <!-- this empty table cell will show the `+` sign which toggles the hidden cells in responsive (collapsed) mode -->

                <div class="position-lc h-95 ml-1px border-l-3 brc-purple-m1">
                  <!-- this decorative highlight border will be shown only when table is collapsed (responsive) -->
                </div>
              </td>

              <td class="pl-3 pl-md-4 align-middle pos-rel">
                <input type="checkbox" data-id="{{ data.id }}" />
                <div class="d-n-collapsed position-lc h-95 ml-1px border-l-3 brc-purple-m1">
                  <!-- this decorative highlight border will be shown only when table is in full mode (not collapsed >> .d-n-collapsed) -->
                </div>
              </td>

              <td class="align-middle">
                {{ forloop.counter }}
              </td>

              <td class="align-middle">
                {{ data.name }}
              </td>

              <td class="align-middle">
                {{ data.groupdetails.alias }}
              </td>

              <td class="align-middle">
                {{ data.groupdetails.description }}
              </td>

              <td class="align-middle">
                <div class="d-flex">
                  <span class="d-lg-inline mx-1">
                    <a href="{% url 'adminpage:account_edit_group' data.id %}" data-action="edit">
                      <button type="button" data-rel="tooltip" data-action="edit" title="Edit" class="btn btn-outline-warning shadow-sm btn-bgc-white">
                          <i class="fas fa-pen-to-square text-100"></i>
                      </button>
                    </a>
                  </span>
                </div>

              </td>
            </tr>
            {% endfor %}
            {% endif %}
          </tbody>
        </table>

      </form>
    </div>

    <div class="mt-45 bcard">
      {% if datagrouplist %}
      <ul class="nav nav-justified nav-tabs nav-tabs-simple" role="tablist">
        {% for key, value in datagrouplist.items %}
        <li class="nav-item mr-1px">
          <a class="d-style btn btn-outline-light btn-a-text-dark btn-a-outline-lightgrey bgc-white radius-0 py-2 text-95 {% if forloop.counter == 1 %}active{% endif %}" id="{{key}}_tabbtn" data-toggle="tab" href="#{{key}}" role="tab" aria-controls="{{key}}" aria-selected="true">
            <span class="v-active position-tl w-102 border-t-3 brc-orange mt-n3px ml-n1px"></span><!-- show this when active -->
            <span class="v-n-active v-hover position-tl w-102 border-t-3 brc-orange-tp3 mt-n2px ml-n1px"></span><!-- show this when hovered & NOT active -->
            {{ value }}
          </a>
        </li>
        {% endfor %}

      </ul>


      <div class="tab-content bgc-white p-35 border-1 brc-grey-l1">
        {% if datauser %}
        {% for key, values in datauser.items %}
        <div class="tab-pane fade text-95 {% if forloop.counter == 1 %}active show{% endif %}" id="{{key}}" role="tabpanel" aria-labelledby="{{key}}_tabbtn">
          <table id="datatable" class="d-style w-100 table text-dark-m1 text-95 border-y-1 brc-black-tp11 collapsed dtr-table tablerole">
            <thead class="sticky-nav text-secondary-m1 text-uppercase text-85">
              <tr>
                <th class="td-toggle-details border-0 bgc-white shadow-sm">
                  <i class="fa fa-angle-double-down ml-2"></i>
                </th>
  
                <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                  Username
                </th>
  
                <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                  Name
                </th>
  
                <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                  Email
                </th>

                <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                  Aksi
                </th>
              </tr>
            </thead>
  
            <tbody class="pos-rel">
              {% if values %}
              {% for data in values %}
              <tr class="d-style bgc-h-default-l4">
                <td class="td-toggle-details pos-rel">
                  <!-- this empty table cell will show the `+` sign which toggles the hidden cells in responsive (collapsed) mode -->

                  <div class="position-lc h-95 ml-1px border-l-3 brc-purple-m1">
                    <!-- this decorative highlight border will be shown only when table is collapsed (responsive) -->
                  </div>
                </td>

                <td class="pl-3 pl-md-4 align-middle pos-rel">
                  <div class="d-n-collapsed position-lc h-95 ml-1px border-l-3 brc-purple-m1">
                    <!-- this decorative highlight border will be shown only when table is in full mode (not collapsed >> .d-n-collapsed) -->
                  </div>
                  <span class="text-105">
                    {{ data.user.username }}
                  </span>
                </td>

                <td>
                  {{ data.user.first_name }} {{ data.user.last_name }}
                </td>

                <td>
                  {{ data.user.email }}
                </td>

                <td class="align-middle">
                  <div class="d-flex">
                    <span class="d-lg-inline mx-1">
                      <a href="{% url 'adminpage:account_edit' data.user.id %}">
                        <button type="button" data-rel="tooltip" data-action="edit" title="Edit" class="btn btn-outline-info shadow-sm btn-bgc-white">
                            <i class="fas fa-pen-to-square text-100"></i>
                        </button>
                      </a>
                    </span>

                    <span class="d-none d-lg-inline mx-1">
                      <a data-action="delete" onclick="deletedata(`{% url 'adminpage:account_delrole' data.user.id data.group.id %}`)">
                        <button type="button" data-rel="tooltip" data-action="delete" title="Delete Role" class="btn btn-outline-danger shadow-sm btn-bgc-white">
                          <i class="fas fa-trash-can text-100"></i>
                        </button>
                      </a>
                    </span>
                  </div>

                </td>


              </tr>
              {% endfor %}
              {% endif %}
            </tbody>
          </table>
        </div>
        {% endfor %}
        {% endif %}
      </div>
      {% else %}
        <div class="alert alert-collapse bgc-white text-dark-tp3 border-1 brc-secondary-l2 shadow-sm radius-0 py-3 d-flex align-items-start mt-3">
          <div class="position-tl w-102 m-n1px border-t-4 brc-warning"></div>
          <div class="bgc-warning px-4 py-25 radius-1px mr-4 shadow-sm">
            <i class="fa fa-exclamation text-180 text-white"></i>
          </div>

          <div class="text-dark-tp3">
            <h3 class="text-warning-d1 text-130">Info!</h3>
            No user has a role
          </div>
        </div>
      {% endif %}
    </div>

  </div>


{% endblock %}


{% block javascript %}
<script>
  function deletedata(url){
    Swal.fire({
      title: 'Are you sure?',
      text: 'This user role will be deleted',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
      if (result.value) {
        window.location.replace(url);
      }
    });
  }

  $(document).ready(function(){
    // helper methods to add/remove bgc-h-* class when selecting/deselecting rows
    var _highlightSelectedRow = function(row) {
      row.classList.add('bgc-success-l3')
      row.classList.remove('bgc-h-default-l4')
    }
    var _unhighlightDeselectedRow = function(row) {
      row.classList.remove('bgc-success-l3')
      row.classList.add('bgc-h-default-l4')
    }

    var $table_role = $('.tablerole').DataTable({
      responsive: true,
      select: {style: 'single'},
      language: {
        search: '<i class="fa fa-search text-blue-m2"></i>',
        searchPlaceholder: " Search"
      }
    }).on('select', function (e, dt, type, index) {
      if ( type == 'row' ) {
        var row = $table_role.row( index ).node()
        _highlightSelectedRow(row)
      }
    }).on('deselect', function (e, dt, type, index) {
      if ( type == 'row' ) {
        var row = $table_role.row( index ).node()
        _unhighlightDeselectedRow(row)
      }
    })



  });
</script>
{% endblock %}